version: '3.7'

services:
  web:
    build:
      dockerfile: docker/Dockerfile
    container_name: file_server_stage_web
    volumes:
      - static_volume:/home/app/web/static
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    # logging:
    #   driver: "awslogs"
    #   options:
    #     awslogs-region: "us-east-1"
    #     awslogs-group: "Backend-Dev-Log"
    #     awslogs-stream: "develop"

  db:
    image: postgres:15
    container_name: file_server_stage_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

  # redis:
  #   container_name: file_server_stage_redis

  # celery:
  #   build:
  #     dockerfile: docker/Dockerfile.celery
  #   container_name: file_server_stage_celery

  # celery-beat:
  #   build:
  #     dockerfile: docker/Dockerfile.celery
  #   container_name: file_server_stage_celery_beat

volumes:
  postgres_data:
  static_volume:
  media_volume:
